version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-nest
    restart: always
    environment:
      POSTGRES_USER     : user
      POSTGRES_PASSWORD : pass
      POSTGRES_DB       : test
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
